### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by jblance** [jblance/powermon#13]
- [x] update installation doc - make sure options are correct
- [x] update usage doc - update -h output, add different examples (listProtocols, listCommands, config on cmd line)
- [x] add full example for config
- [x] add cli option to generate a config file
- [x] add cli to usage doc
- [x] update pi18 from mppsolar
- [x] update html files
- [x] remove separate heltec protocol class
- [x] combine pi30 and pi30max??
- [x] finish [neey balancer](https://github.com/syssi/esphome-jk-bms/blob/main/components/heltec_balancer_ble/heltec_balancer_ble.cpp)

**Comment by jblance** [comment]
pi18
- flag
- vfw
